# settings.yml
# Use this to define changeable values such as max_power.
# All values are in metric
# Unit of length is millimeters, not meters
# Unit of rotation is degrees (angular velocity is in degrees per second)

# Encoder pulses per full revolution http://ftcforum.usfirst.org/archive/index.php/t-5189.html
encoder:
  output_pulses: 1120
  encoder_pulses: 28

# The drivetrain's settings.
drivetrain:
  motor_wheel_ratio: 2.5
  motor_max_power: 1
  motor_left:
    offset: 0.0
    map_name: drive_left
    encodered: true
    reversed: false
    encoder_reversed: true
  motor_right:
    offset: 0.0
    map_name: drive_right
    encodered: false
    reversed: true
    encoder_reversed: true
  wheel:
    diameter: 101.6 # 4 inches

# Winch settings
winch:
  enabled: true
  linear_movement:
    motor_reversed: true
    motor_tape_ratio: 2.5
    mot_max_power: 1
    max_extend_power: 0.6
    max_retract_power: 1
  angular_movement:
    max_ang_vel: 20.0
    full_rotate: 180.0
    max_rotate: 90.0
    preset: 15.0
  left_servo:
    reversed: true
    offset: 15.75
  right_servo:
    reversed: false
    offset: 0.0

# Trigger Arm settings (It's a servo)
trigger_arm:
  enabled: true
  side: right


# Plow settings (It's a servo)
plow:
  enabled: true
  reversed: false
  offset: 30.0
  full_rotate: 180.0
  down_angle: 0.0
  up_angle: 130.0

test: true